name: CI Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: Install dependencies
      run: npm install

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        eslint: true # Enable linters
        # prettier: true
    - name: eslint
      uses: icrawl/action-eslint@v1
      #with:
      #  custom-glob: apps # only if a different glob is needed, default: src

    - run: npm run build --if-present
    - run: npm run test

    # - name: Run a multi-line script
    #   env:
    #     RW_TOKEN: ${{ secrets.RW_TOKEN }}
    #   shell: bash
    #   run: |
    #     curl --request POST \
    #     --url https://api.github.com/repos/myaccount/mytestrepo/issues \
    #     --header 'authorization: Bearer'" $RW_TOKEN" \
    #     --header 'content-type: application/json' \
    #     --data '{
    #       "title": "Automated issue for commit: ${{ github.sha }}",
    #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
    #       }'
