name: CI Workflow

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]
    types: ['synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: Install dependencies
      run: npm ci --no-audit --prefer-offline

    - name: Run Lint Check
      run: npm run lint-report
      continue-on-error: true
    
    - name: Run Test Check
      run: npm run test-report
      continue-on-error: true

    - name: Annotate code checks
      uses: agyemanjp/ci-checks-action@2.0.2
      with:
        ghToken: "${{ secrets.GITHUB_TOKEN }}"
        checks: '[
              {
                "name": "lint",
                "fileName": ".lint-report.json",
                "prChangesOnly": true
              },
              {
                "name": "test",
                "fileName": ".test-report.json",
                "prChangesOnly": false
              }
            ]'
