# This workflow will do a clean install of dependencies, build the source, and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        # Enable linters
        eslint: true
        # prettier: true

    - run: npm run build --if-present
    - run: npm test
